"""create task

Revision ID: 437c2de17758
Revises: ec9e682588a9
Create Date: 2024-07-23 22:20:10.759913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437c2de17758'
down_revision = 'ec9e682588a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
